name: Despliegue en Servidor

on:
  push:
    branches:
      - main  # o el nombre de tu rama principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código fuente
      uses: actions/checkout@v2

    - name: Configuración de Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 14  # Puedes ajustar esto según la versión que necesites

    - name: Instalación de dependencias del servidor
      run: npm install

    - name: Instalación de dependencias del cliente
      run: npm install --prefix client

    - name: Construcción del cliente
      run: npm --prefix client install && npm --prefix client run build

    - name: Despliegue en el servidor
      run: scp -r ./ user@tu-servidor:/ruta/del/despliegue

    - name: Reinicio del servidor
      run: ssh user@tu-servidor "pm2 restart nombre-de-tu-app"
